### ISSUE TITLE
 It may be not  compatible with Obsidian Plugin-Sliding Panes. 

### ISSUE THREAD

**Issue by wwjCMP** [FHachez/obsidian-convert-url-to-iframe#1] opened 2020-12-20 13:10 UTC
If the Obsidian Plugin-Sliding Panes has been install, the width of iframe can not be change.

**Comment by kankaristo** [comment] 2021-01-01 22:52
This doesn't seem to be caused by the Sliding Panes (Andy's Mode) plugin, the issue persists even if that plugin is disabled (unless Obsidian doesn't completely disable plugins).

But whether that's the case or not, the issue should be fixed with https://github.com/FHachez/obsidian-convert-url-to-iframe/pull/5.

**Closed** 2021-01-22 12:22 UTC
